### ISSUE TITLE
symbolic link "./install" to missing target file

### ISSUE THREAD

**Issue by lglussen** [voko/python-teamforge#1]
I'm trying to build using the provided Makefile but I get the error:

```
make: ./install: Command not found
make: ./install: Command not found
./install --makefile
make: ./install: Command not found
Makefile:11: recipe for target 'Makefile' failed
make: *** [Makefile] Error 127
````

The issue seems to be the `./install` symbolic link is pointing to a file `/usr/bin/custom-install` which doesn't exist on my system (Fedora 23 Desktop).  I haven't found anything in the documentation that mentions this file, and it doesn't appear to be created by the make process.  

Am I missing a required dependency or is this a file I need to create?

**Comment by voko** [comment]
The addon needs to Unix Development Tools (mainly make) and the Teamforge Customization Installer. Although the TCI can be installed without teamforge being present, I personally never did that but instead work on a centos machine that has teamforge installed (TCI comes with it).

Visit https://ctf.open.collab.net/sf/sfmain/do/go/wiki1998 to learn more about the customization installer. 

I also setup the rpm to automatically initiate the install. On a system without the customization installer, simply create a executable script file at ```/usr/bin/custom-install``` that returns 0. This should get rid of the error (not the cause:).
